FROM rust:1.73.0-bookworm as builder

WORKDIR /heimbjartur

RUN apt update && apt install -y lsb-release software-properties-common sudo libzstd-dev

RUN echo "deb http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-16 main" > /etc/apt/sources.list.d/llvm-toolchain-bookworm-16.list \
    && echo "deb-src http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-16 main" >> /etc/apt/sources.list.d/llvm-toolchain-bookworm-16.list

RUN wget https://apt.llvm.org/llvm.sh && \
    chmod +x llvm.sh && \
    bash llvm.sh 16 all

RUN apt clean && rm -rf var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN rustup install stable && \
    rustup toolchain install nightly --component rust-src && \
    cargo install --no-default-features bpf-linker